version: "2.4"

services:

  uuv_ardusub_simulator:
    image: hub.ci.dfl.ae/roboticslab/ros2_humble_x86_no_gpu:ardusub-simulator
    command: bash -c "cd /ws/ardupilot/ArduSub && sudo python3 ../Tools/autotest/sim_vehicle.py -L RATBeach --out=udp:0.0.0.0:14550 --map --console"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - general.env
    container_name: uuv_ardusub_simulator
    volumes:
      - "${HOME}/UnderWaterVehicle:/ws_uuv"
      - "/dev:/dev"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"

  uuv_ardusub_simulator_apm:
    image: hub.ci.dfl.ae/roboticslab/ros2_humble_x86_no_gpu:ardusub-simulator
    command: bash -c "sleep 20 && cd /UnderWaterVehicle/ws && source install/setup.bash && ros2 launch mavros apm.launch"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - general.env
    container_name: uuv_ardusub_simulator_apm
    volumes:
      - "${HOME}/UnderWaterVehicle:/ws_uuv"
      - "/dev:/dev"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"

  uuv_ardusub_dev:
    image: hub.ci.dfl.ae/roboticslab/ros2_humble_x86_no_gpu:mavros
    command: bash -c "sleep infinity"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - general.env
    container_name: uuv_ardusub_dev
    volumes:
      - "${HOME}/UnderWaterVehicle:/UnderWaterVehicle"
      - "/dev:/dev"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
