int32     current
uint32    charge_remain
uint32    full_charge
int32     charge_i
int32     charge_v
int32     pack_v
uint32    batt_v
uint16    cycle_count
uint16    avg_time_empty
uint16    avg_time_full
uint16    soc
uint16    soh
uint16    batt_stat
uint16    batt_alarm
uint16    batt_safety

uint16    temp_max
uint16    temp_min

uint8     stat_batt_full_charge
uint8     stat_cycle_count
uint8     stat_int_r_update
uint8     stat_empty_batt
uint8     stat_full_charge
uint8     stat_int_r_success
uint8     stat_init_done
uint8     stat_remain_time
uint8     stat_remain_capac
uint8     stat_weak_current
uint8     stat_calib_enable
uint8     stat_calib_cc_offset
uint8     stat_comm_data_read
uint8     stat_prog_activ
    
uint8     alrm_single_batt_uv
uint8     alrm_discharge_oc
uint8     alrm_batt_oc
uint8     alrm_discharge_ot
uint8     alrm_remaining_cap
uint8     alrm_discharge_ut
uint8     alrm_single_batt_ov
uint8     alrm_charge_oc
uint8     alrm_charge_ot
uint8     alrm_charge_ut

