version: "2.4"

services:

  uuv_ardusub_simulator:
    image: hub.ci.dfl.ae/roboticslab/bluerov2:apm
    command: bash -c "sleep 5.0 && cd ~/ardupilot && Tools/autotest/sim_vehicle.py -L RATBeach -v ArduSub -f vectored_6dof --model=JSON --out=udp:0.0.0.0:14550 --console"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - general.env
    container_name: uuv_ardusub_simulator
    volumes:
      - "/dev:/dev"
      - "/run/user:/run/user"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${HOME}/UnderWaterVehicle:/UnderWaterVehicle"

  uuv_ardusub_gazebo:
    image: hub.ci.dfl.ae/roboticslab/bluerov2:gz
    command: bash -c "source /UnderWaterVehicle/ws/install/setup.bash && ros2 launch bluerov2_gz gazebo_launch.py"
    #command: bash -c "sleep infinity"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - general.env
    container_name: uuv_ardusub_gazebo
    volumes:
      - "/dev:/dev"
      - "/run/user:/run/user"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${HOME}/UnderWaterVehicle:/UnderWaterVehicle"
      
  uuv_ardusub_simulator_apm:
    image: hub.ci.dfl.ae/roboticslab/bluerov2:apm
    command: bash -c "sleep 10 && cd /home/bluerov2/ws && source install/setup.bash && ros2 launch mavros apm.launch"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - general.env
    container_name: uuv_ardusub_simulator_apm
    volumes:
      - "/dev:/dev"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${HOME}/UnderWaterVehicle:/UnderWaterVehicle"
      

  uuv_ardusub_dev:
    image: hub.ci.dfl.ae/roboticslab/bluerov2:gz
    command: bash -c "sleep infinity"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - general.env
    container_name: uuv_ardusub_dev
    volumes:
      - "${HOME}/UnderWaterVehicle:/UnderWaterVehicle"
      - "/dev:/dev"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
